"""Add routing_shortlist to tickets

Revision ID: 7a548e571b25
Revises: c8cfcd496f41
Create Date: 2026-09-20 16:23:43.666469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a548e571b25'
down_revision: Union[str, None] = 'c8cfcd496f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('routing_shortlist', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'routing_shortlist')
    # ### end Alembic commands ###
