"""Add public_good_consent

Revision ID: c8cfcd496f41
Revises: 0002
Create Date: 2026-09-20 02:55:52.098487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8cfcd496f41'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('public_good_consent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tickets', sa.Column('public_good_consent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'public_good_consent_at')
    op.drop_column('tickets', 'public_good_consent')
    # ### end Alembic commands ###
